services:
  db:
    image: postgres:17
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env.db
      - ./api/.env
    depends_on:
      - db
    ports:
      - "5001:5000"
    # command: npm run start:dev
    # volumes:
    #   - .:/app
    networks:
      - data
      - backend

volumes:
  postgres_data:

networks:
  backend:
  data:
